apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: support-ticketing-dev

resources:
  - namespace.yaml
  - dependencies.yaml
  - workloads.yaml
  - ingress.yaml

configMapGenerator:
  - name: app-config
    literals:
      - JWT_ISSUER=SupportTicketing
      - JWT_AUDIENCE=SupportTicketing.Clients
      - CORS_ALLOWED_ORIGIN=__CLIENT_ENDPOINT__
      - SQLSERVER_HOST=sqlserver
      - RABBITMQ_HOST=rabbitmq
      - INITIAL_ADMIN_EMAIL=__INITIAL_ADMIN_EMAIL__
      - INITIAL_ADMIN_FULL_NAME=__INITIAL_ADMIN_FULL_NAME__

generatorOptions:
  disableNameSuffixHash: true
