apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: support-ticketing-dev

resources:
  - namespace.yaml
  - dependencies.yaml
  - workloads.yaml

configMapGenerator:
  - name: app-config
    literals:
      - JWT_ISSUER=SupportTicketing
      - JWT_AUDIENCE=SupportTicketing.Clients
      - CORS_ALLOWED_ORIGIN=__CLIENT_ENDPOINT__
      - SQLSERVER_HOST=sqlserver
      - RABBITMQ_HOST=rabbitmq

generatorOptions:
  disableNameSuffixHash: true

patches:
